// Font
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

const String kFontFamily = "Inter";
List<String?> kFontFamilys = [
  GoogleFonts.montserrat().fontFamily,
  GoogleFonts.openSans().fontFamily,
  GoogleFonts.workSans().fontFamily,
  GoogleFonts.dmSans().fontFamily,
  GoogleFonts.roboto().fontFamily,
  GoogleFonts.bebasNeue().fontFamily,
  GoogleFonts.robotoCondensed().fontFamily,
  GoogleFonts.robotoSlab().fontFamily,
  GoogleFonts.lato().fontFamily,
  GoogleFonts.poppins().fontFamily,
  GoogleFonts.playfairDisplay().fontFamily,
  GoogleFonts.oswald().fontFamily,
  GoogleFonts.sourceSans3().fontFamily,
  GoogleFonts.lora().fontFamily,
  GoogleFonts.raleway().fontFamily,
  GoogleFonts.merriweather().fontFamily,
  GoogleFonts.rubik().fontFamily,
  GoogleFonts.firaSans().fontFamily,
  GoogleFonts.nunito().fontFamily,
  GoogleFonts.quicksand().fontFamily,
  GoogleFonts.ubuntu().fontFamily,
  GoogleFonts.alegreya().fontFamily,
  GoogleFonts.inter().fontFamily,
  GoogleFonts.ptSerif().fontFamily,
  GoogleFonts.leagueSpartan().fontFamily,
  GoogleFonts.titilliumWeb().fontFamily,
  GoogleFonts.alegreya().fontFamily,
  GoogleFonts.inconsolata().fontFamily,
];

List<String> kFontWeights = const [
  'thin',
  'light',
  'regular',
  'medium',
  'semi-bold',
  'bold',
  'extra bold',
];

List<String> kAlignments = const [
  'left',
  'right',
  'center',
];

// Data
Map<String, dynamic> kDefaultDesign = {};
List<Map<String, dynamic>> kAdditionalBlocks = const [];

final Uint8List kTransparentImage = Uint8List.fromList(<int>[
  0x89,
  0x50,
  0x4E,
  0x47,
  0x0D,
  0x0A,
  0x1A,
  0x0A,
  0x00,
  0x00,
  0x00,
  0x0D,
  0x49,
  0x48,
  0x44,
  0x52,
  0x00,
  0x00,
  0x00,
  0x01,
  0x00,
  0x00,
  0x00,
  0x01,
  0x08,
  0x06,
  0x00,
  0x00,
  0x00,
  0x1F,
  0x15,
  0xC4,
  0x89,
  0x00,
  0x00,
  0x00,
  0x0A,
  0x49,
  0x44,
  0x41,
  0x54,
  0x78,
  0x9C,
  0x63,
  0x00,
  0x01,
  0x00,
  0x00,
  0x05,
  0x00,
  0x01,
  0x0D,
  0x0A,
  0x2D,
  0xB4,
  0x00,
  0x00,
  0x00,
  0x00,
  0x49,
  0x45,
  0x4E,
  0x44,
  0xAE,
  0x42,
  0x60,
  0x82,
]);

// Other
Map<Key, bool> kExpansionStates = {};
